pinit_homepage:
    path: /
    defaults: { _controller: PinitProjectBundle:Default:index }

pinit_project_homepage:
    path:     /hello/{name}
    defaults: { _controller: PinitProjectBundle:Default:index }

random:
    path:     /random/{limit}
    defaults: { _controller: PinitProjectBundle:Random:index }

pinit_help:
    path:    /help
    defaults: { _controller: PinitProjectBundle:Help:index }

pinit_project_create:
    path:   /project/create
    defaults: { _controller: PinitProjectBundle:Default:create}


